package:
  name: pyzbar
  version: 0.1.0

source:
  git_url: https://github.com/NaturalHistoryMuseum/pyzbar.git
  git_branch: master

requirements:
  build:
    - setuptools
  run:
    - python
    - zbar  # تعتمد على مكتبة zbar غير النقية

build:
  script: |
    pip install .

test:
  commands:
    - pytest  # إذا كان لديك اختبارات
